import Link from 'next/link'

export default function Home() {
  return (
    <div className="w-full max-w-4xl p-8">
      <header className="mb-12 border-b border-green-900 pb-4">
        <h1 className="text-4xl font-bold glitch-text">KRYPTO-VELAMEN</h1>
        <p className="text-sm opacity-70 mt-2">
          [SYSTEM STATUS: ONLINE] [POLARITY: DUAL]
        </p>
      </header>

      <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="border border-green-800 p-6 bg-black/50 hover:bg-green-900/10 transition-colors">
          <h2 className="text-xl font-bold mb-4">// ARCHIVE_ENGINE</h2>
          <p className="mb-4 text-sm opacity-80">
            Access the deep research corpus and creative fragments.
          </p>
          <button className="px-4 py-2 bg-green-900 text-black font-bold hover:bg-green-500">
            ENTER ARCHIVE
          </button>
        </div>

        <div className="border border-green-800 p-6 bg-black/50 hover:bg-green-900/10 transition-colors">
          <h2 className="text-xl font-bold mb-4">// COMMUNITY_SUBSTRATE</h2>
          <p className="mb-4 text-sm opacity-80">
            Connect with the network. Private journals and threaded discussions.
          </p>
          <button className="px-4 py-2 border border-green-500 text-green-500 hover:bg-green-500 hover:text-black">
            LOGIN
          </button>
        </div>
      </section>

      <footer className="mt-24 text-center text-xs opacity-40">
        Generated by Organ II — POIESIS.
      </footer>
    </div>
  )
}
