import Link from 'next/link'
import ArchiveGrid from '@/components/ArchiveGrid'
import { fetchFragments } from '@/lib/api'

export default async function Home() {
  const fragments = await fetchFragments()

  return (
    <div className="w-full max-w-6xl p-8">
      <header className="mb-12 border-b border-green-900 pb-4 flex justify-between items-end">
        <div>
          <h1 className="text-4xl font-bold glitch-text">KRYPTO-VELAMEN</h1>
          <p className="text-sm opacity-70 mt-2">
            [SYSTEM STATUS: ONLINE] [POLARITY: DUAL] [v1.0.0]
          </p>
        </div>
        <nav className="flex gap-6 text-sm">
          <Link href="/identity" className="hover:text-white transition-colors">THE_MASK</Link>
          <Link href="/community" className="hover:text-white transition-colors">SUBSTRATE</Link>
          <Link href="/atlas" className="hover:text-white transition-colors">ATLAS</Link>
        </nav>
      </header>

      <div className="mb-12">
        <h2 className="text-xs font-bold mb-6 tracking-[0.3em] text-green-800 uppercase">
          // RECENT_TRANSMISSIONS
        </h2>
        <ArchiveGrid fragments={fragments} />
      </div>

      <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="border border-green-800 p-6 bg-black/50 hover:bg-green-900/10 transition-colors">
          <h2 className="text-xl font-bold mb-4">// ARCHIVE_ENGINE</h2>
          <p className="mb-4 text-sm opacity-80">
            Access the deep research corpus and creative fragments. Explore the encoding schema across five author clusters.
          </p>
          <button className="px-4 py-2 bg-green-900 text-black font-bold hover:bg-green-500">
            ENTER ARCHIVE
          </button>
        </div>

        <div className="border border-green-800 p-6 bg-black/50 hover:bg-green-900/10 transition-colors">
          <h2 className="text-xl font-bold mb-4">// COMMUNITY_SUBSTRATE</h2>
          <p className="mb-4 text-sm opacity-80">
            Collaborative journals and threaded discussions. Share your substrate with the network under calibrated visibility.
          </p>
          <button className="px-4 py-2 border border-green-500 text-green-500 hover:bg-green-500 hover:text-black">
            LOGIN
          </button>
        </div>
      </section>

      <footer className="mt-24 pt-8 border-t border-green-950 text-center text-xs opacity-40">
        Generated by Organ II — POIESIS. Transmitting from the hinterland.
      </footer>
    </div>
  )
}
